name: AllMining
version: 1.3
main: com.masahirosaito.spigot.allmining.AllMining
authors: [MasahiroSaito]
description: Spigot plugin to mine all the same ore at once
website: https://github.com/MasahiroSaito/AllMining
commands:
  am:
    description: AllMining Command
    usage: /<command> (on/off)